# Generated by Django 6.0.4 on 2026-06-09 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('seller_id', models.UUIDField()),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked')], db_index=True, default='PENDING', max_length=20)),
                ('queue_priority', models.PositiveSmallIntegerField(default=3, help_text='1 — highest priority, 4 — lowest')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, null=True)),
                ('json_before', models.JSONField(blank=True, null=True)),
                ('json_after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queue_priority', 'created_at'],
            },
        ),
    ]
