# Generated by Django 6.0.4 on 2026-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_queue', '0002_blockingreason_ticket_blocking_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEventLog',
            fields=[
                ('idempotency_key', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('product_id', models.UUIDField(db_index=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'processed_at'], name='moderation__product_788010_idx')],
            },
        ),
    ]
