# Generated by Django 6.0.4 on 2026-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'В сборке'), ('CANCELLED', 'Отменён'), ('CANCEL_PENDING', 'Отмена ожидает повтора'), ('RESERVE_FAILED', 'Ошибка резерва')], default='PAID', max_length=30),
        ),
    ]
