# Generated by Django 6.0.4 on 2026-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'В сборке'), ('CANCELLED', 'Отменён'), ('CANCEL_PENDING', 'Отмена ожидает повтора'), ('DELIVERED', 'Доставлен'), ('RESERVE_FAILED', 'Ошибка резерва')], default='PAID', max_length=30),
        ),
    ]
