# Generated by Django 6.0.4 on 2026-06-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProductEvent',
            fields=[
                ('idempotency_key', models.UUIDField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'В сборке'), ('DELIVERING', 'Доставляется'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменён'), ('CANCEL_PENDING', 'Отмена ожидает повтора'), ('RESERVE_FAILED', 'Ошибка резерва')], default='PAID', max_length=30),
        ),
    ]
