# Generated by Django 6.0.4 on 2026-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.UUIDField(help_text='ID продавца из сервиса авторизации'),
        ),
    ]
