# Generated by Django 6.0.4 on 2026-06-02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_seller_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="blocking_reason_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="moderator_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="characteristic",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]

