# Generated by Django 6.0.4 on 2026-06-01 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blocking_reason_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='moderator_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('ON_MODERATION', 'На модерации'), ('MODERATED', 'Одобрен'), ('BLOCKED', 'Заблокирован'), ('HARD_BLOCKED', 'Жёстко заблокирован')], default='CREATED', help_text='Статус модерации', max_length=20),
        ),
    ]
