# Generated by Django 6.0.4 on 2026-06-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_fields_and_embedded_uuids"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockingReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Причина блокировки",
                "verbose_name_plural": "Причины блокировки",
            },
        ),
        migrations.CreateModel(
            name="ProductFieldReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=64)),
                ("sku_id", models.UUIDField(blank=True, null=True)),
                ("comment", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_reports",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замечание модератора",
                "verbose_name_plural": "Замечания модератора",
                "ordering": ["field_name"],
            },
        ),
    ]
