# Generated by Django 6.0.4 on 2026-06-09 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.UUIDField()),
                ('sku_id', models.UUIDField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'sku_id'], name='cart_cartit_user_id_345039_idx'), models.Index(fields=['session_id', 'sku_id'], name='cart_cartit_session_d1a870_idx')],
            },
        ),
    ]
