# Generated by Django 6.0.4 on 2026-06-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
