# Generated by Django 6.0.4 on 2026-05-02 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('article', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
            },
        ),
        migrations.CreateModel(
            name='SKUCharacteristic',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='skus.sku')),
            ],
            options={
                'verbose_name': 'Характеристика SKU',
                'verbose_name_plural': 'Характеристики SKU',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('url', models.URLField(verbose_name='URL изображения')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skus.sku')),
            ],
            options={
                'verbose_name': 'Изображение SKU',
                'verbose_name_plural': 'Изображения SKU',
            },
        ),
    ]
