# Generated by Django 6.0.4 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sku",
            name="cost_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sku",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

