# Generated by Django 6.0.4 on 2026-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
