# Generated by Django 6.0.4 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='stock_quantity',
            new_name='active_quantity',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
