# Generated by Django 6.0.4 on 2026-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0002_sku_cost_price_sku_discount_sku_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimage',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL изображения'),
        ),
    ]
