# Generated by Django 6.0.4 on 2026-06-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0003_reserve_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilledOrder',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('fulfilled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Операция резервирования',
                'verbose_name_plural': 'Операции резервирования',
            },
        ),
        migrations.AlterModelOptions(
            name='reserveoperation',
            options={},
        ),
    ]
