# Generated by Django 6.0.4 on 2026-06-13 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skus', '0003_reserve_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('PARTIALLY_ACCEPTED', 'Принята частично'), ('ACCEPTED', 'Принята полностью'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='skus.sku')),
            ],
            options={
                'unique_together': {('invoice', 'sku')},
            },
        ),
    ]
